In [1]:
import numpy as np 
import random
import matplotlib.pyplot as plt
import math

In [2]:
# 5 input neurons in the input layer
# 2 hidden layers with 6 neurons each
# 2 output neurons in the output layer
# all activation functions are sigmoid


dataset_unfiltered = np.array([
	[0,		0,		0,		0,		0,		0,		1],
	[0,		0,		0,		0,		1,		0,		1],
	[0,		0,		0,		1,		0,		0,		1],
	[0,		0,		0,		1,		1,		0,		1],
	[0,		0,		1,		0,		0,		0,		1],
	[0,		0,		1,		0,		1,		0,		1],
	[0,		0,		1,		1,		0,		0,		1],
	[0,		0,		1,		1,		1,		0,		1],
	[0,		1,		0,		0,		0,		1,		0],
	[0,		1,		0,		0,		1,		0,		1],
	[0,		1,		0,		1,		0,		1,		0],
	[0,		1,		0,		1,		1,		1,		0],
	[0,		1,		1,		0,		0,		0,		1],
	[0,		1,		1,		0,		1,		0,		1],
	[0,		1,		1,		1,		0,		1,		0],
	[0,		1,		1,		1,		1,		1,		0],
	[1,		0,		0,		0,		0,		0,		1],
	[1,		0,		0,		0,		1,		0,		1],
	[1,		0,		0,		1,		0,		1,		0],
	[1,		0,		0,		1,		1,		0,		1],
	[1,		0,		1,		0,		0,		1,		0],
	[1,		0,		1,		0,		1,		1,		0],
	[1,		0,		1,		1,		0,		1,		0],
	[1,		0,		1,		1,		1,		1,		0],
	[1,		1,		0,		0,		0,		0,		1],
	[1,		1,		0,		0,		1,		0,		1],
	[1,		1,		0,		1,		0,		1,		0],
	[1,		1,		0,		1,		1,		0,		1],
	[1,		1,		1,		0,		0,		1,		0],
	[1,		1,		1,		0,		1,		1,		0],
	[1,		1,		1,		1,		0,		1,		0],
	[1,		1,		1,		1,		1,		1,		0]
	])

In [3]:
def generateRandom2DMatrix(m, n):
	return [ [random.randint(1,100)/100 for k in range(n)] for i in range(m) ]

def sigmoid(z):
	return 1/(1+np.exp(-z))

def CostFunction(NN_output,output):
	return output*(np.log10(NN_output)) + (1-output)*(np.log10(1 - NN_output))

In [4]:
data_set = [ [0 for k in range(6)] for i in range(len(dataset_unfiltered)) ]
index_data_set = 0



for k in range(len(dataset_unfiltered[:,0])):

	for i in range(dataset_unfiltered[k][5]):
		#temp = np.append( dataset_unfiltered[k][0:5], 1)
		data_set[index_data_set] = np.append( dataset_unfiltered[k][0:5], 1)
		index_data_set += 1

	for j in range(dataset_unfiltered[k][6]):
		#temp = dataset_unfiltered[k][0:5]
		data_set[index_data_set] = np.append( dataset_unfiltered[k][0:5], 0)
		index_data_set += 1

In [5]:
# Splitting dataset into training dataset and testing dataset:
# But first, we need to shuffle the entire dataset!

random.seed(99)
random.shuffle(data_set)

training_data_set = data_set[0:(math.ceil(0.70*len(data_set)))]
testing_data_set  =	data_set[(math.ceil(0.70*len(data_set))): len(data_set)]

In [6]:
print("Training dataset:   ", len(training_data_set))
print("Testing dataset:    ", len(testing_data_set))

Training dataset:    23
Testing dataset:     9


In [7]:
inputs = [ [0 for k in range(5)] for i in range(len(training_data_set)) ]
desired_outputs = [0 for k in range(len(training_data_set))]


inputs_testing = [ [0 for k in range(5)] for i in range(len(testing_data_set)) ]
desired_outputs_testing = [0 for k in range(len(testing_data_set))]



for i in range(len(training_data_set)):
	inputs[i] = training_data_set[i][0:5]
	desired_outputs[i] = training_data_set[i][5]

for i in range(len(testing_data_set)):
	inputs_testing[i] = training_data_set[i][0:5]
	desired_outputs_testing[i] = training_data_set[i][5]

In [8]:
bias_space = 1

nInputs_neurons = 5 
nNeurons_second_layer = 6 
nNeurons_third_layer  = 6 
output_neurons = 1 

nInputs_neurons += bias_space
nNeurons_second_layer += bias_space
nNeurons_third_layer  += bias_space
output_neurons += bias_space     # Not needed but will does make the algorith easier to write. We will ignore the bias here.




In [9]:
Weights = [ [] for i in range(3)]

#the first column is the Bias. So it will be set to 1.
Weights[0] = np.array(generateRandom2DMatrix(nNeurons_second_layer, nInputs_neurons ))
Weights[1] = np.array(generateRandom2DMatrix(nNeurons_third_layer, nNeurons_second_layer ))
Weights[2] = np.array(generateRandom2DMatrix(output_neurons, nNeurons_third_layer ))

Weights = np.array(Weights)

In [10]:
input_layer = [ 0 for i in range(nInputs_neurons)]
first_hidden_layer = [ 0 for i in range(nNeurons_second_layer)]
second_hidden_layer = [ 0 for i in range(nNeurons_third_layer)]
output_layer = [ 0 for i in range(output_neurons)]

In [11]:
# These are bias
input_layer = np.append(1, inputs[0])
first_hidden_layer[0] = 1
second_hidden_layer[0] = 1

neurons = [input_layer, first_hidden_layer, second_hidden_layer, output_layer]
neurons = (neurons)
#neuron["layer"]["Which neuron of the layer/ FIRST ONE IS THE BIAS"]
neurons[0][0] = 1
neurons[1][0] = 1
neurons[2][0] = 1
neurons[3][0] = 1

In [12]:
def forwardPropagation(data_number = 0, training_data = True, showComputation = False, matrix_neurons = neurons, W = Weights):
	if(training_data == True):
		input_i = inputs[data_number]
	else:
		input_i = inputs_testing[data_number]

	matrix_neurons[0] = np.append(1 , input_i)
	matrix_neurons[1][0] = 1
	matrix_neurons[2][0] = 1
	matrix_neurons[3][0] = 1
	
	if(showComputation == True):
		print(matrix_neurons)

	for layer in range(len(W)):
		for neuron_j in range(len(matrix_neurons[layer+1])):
			next_layer_neuron = layer + 1
			z_j = np.dot( matrix_neurons[layer] , W[layer][neuron_j,:] )
			matrix_neurons[next_layer_neuron][neuron_j] = sigmoid(z_j)
			if(showComputation == True):
				print(matrix_neurons[layer] ," . " , W[layer][neuron_j,:], "  = s([",next_layer_neuron, "][",neuron_j,"]]) = ", sigmoid(z_j))
				print("")

	matrix_neurons[1][0] = 1
	matrix_neurons[2][0] = 1
	matrix_neurons[3][0] = 1

	return matrix_neurons, W

In [13]:
# test
forwardPropagation(0)


def printNeurons(matrix_neurons = neurons):
	layer_names = ["Inputs        ", "Hidden layer 1", "Hidden layer 2", "Outputs       "]
	for i in range(len(matrix_neurons)):
		print(layer_names[i] , ":        ", matrix_neurons[i])
        
    
printNeurons()

Inputs         :         [1 1 1 0 0 0]
Hidden layer 1 :         [1, 0.6963549298238342, 0.8220063142137535, 0.7130001627522816, 0.8277836082661223, 0.5572478545985555, 0.7685247834990178]
Hidden layer 2 :         [1, 0.8872244509440987, 0.9612400717011033, 0.9721735867571986, 0.8320721031373728, 0.8700163598547583, 0.9234753293152094]
Outputs        :         [1, 0.923769115516216]


In [14]:
# Initializing delta
def get_copy_of_neurons_matrix_null(matrix):
	m = matrix.copy()
	for i in range(len(m)):
		m[i] = np.matrix(m[i])
		m[i].fill(0)
	return m



delta_error_matrix = get_copy_of_neurons_matrix_null(neurons)

In [15]:
def computeDeltaMatrix(training_example = 0, showComputation = False, W = Weights, matrix_neurons = neurons, Delt = delta_error_matrix):
	
	if(showComputation == True):
		print("STARTING: ")
	#training_example = 1000
	input_i = inputs[training_example] 
	desired_outputs_i = desired_outputs[training_example]

	if(showComputation == True):
		print(W)
		print("Training example: ", training_example)
		print("Inputs and outputs: ", input_i, desired_outputs_i)

	for layer in reversed(range(1,len(matrix_neurons))):
		if(showComputation == True):
			print(layer)
		if(layer == len(matrix_neurons) - 1):
			if(showComputation == True):
				print(np.subtract(matrix_neurons[layer][1:len(matrix_neurons[layer])] , desired_outputs_i))
			Delt[layer] = np.subtract(matrix_neurons[layer][1:len(matrix_neurons[layer])] , desired_outputs_i)
			Delt[layer] = np.append(0, Delt[layer])
		else:
				w = W[layer].copy() #[1:len(W[layer])].copy()
				
				w_T = w.transpose() 
				if(showComputation == True):
					print("w: ", w)
					print("w_T:")
					print(w_T)
					print("delta ",layer + 1,":" )
					print(Delt[layer + 1])
				x = np.matmul(w_T, Delt[layer + 1])
				#x = x[1:len(x)]

				# Derivative_Sigmoid_of_neuron_layer(z) = neurons_of_layer*(1-neurons_of_layer)
				neurons_of_layer = np.array(matrix_neurons[layer].copy())#[1:len(matrix_neurons[layer])].copy())
				vector_of_one 	 = np.array(neurons_of_layer.copy())
				vector_of_one.fill(1)
				y = np.subtract(vector_of_one, neurons_of_layer)
				Derivative_Sigmoid_of_neuron_layer = np.multiply(neurons_of_layer , y)

				# Putting the whole equation together:
				Delt[layer] = np.multiply(x , Derivative_Sigmoid_of_neuron_layer)
		if(showComputation == True):
			print("delta[",layer,"]", Delt[layer])
	return Delt

In [16]:
delta = computeDeltaMatrix() 
#print(np.matrix(delta))


def training(nomber_of_training_set = len(training_data_set), matrix_neurons = neurons, W = Weights, regularization_param = 5):
	mat_weights_null = get_copy_of_neurons_matrix_null(W)
	
	for training_set in range(nomber_of_training_set):
		#print(training_set)
		matrix_neurons, W 	= forwardPropagation(training_set, True, False, matrix_neurons, W)
		delta 				= computeDeltaMatrix(training_set)

		# Backpropagation algorithm
		for layer in reversed(range(1, len(matrix_neurons))):
			neuron_vector = neurons[layer-1].copy()
			delta_vector  = delta[layer].copy()

			neuron_vector = np.matrix(neuron_vector)
			delta_vector  = np.matrix(delta_vector).transpose()

			multiplication_term = np.matmul(delta_vector, neuron_vector)
			mat_weights_null[layer-1] = mat_weights_null[layer-1] + multiplication_term

	c = (1/nomber_of_training_set)
	#derivative_J = (1/nomber_of_training_set)*mat_weights_null
	derivatives_Cost_Weight = get_copy_of_neurons_matrix_null(W)

	for layer in range(len(mat_weights_null)):
		for m in range(len(mat_weights_null[layer][:,0])):
			for n in range(len(mat_weights_null[layer][0,:])):
				if(n != 0):
					derivatives_Cost_Weight[layer][m][n] = c*mat_weights_null[layer][m][n] + regularization_param*W[layer][m][n]
				else:
					derivatives_Cost_Weight[layer][m][n] = c*mat_weights_null[layer][m][n]
	return derivatives_Cost_Weight

In [17]:
derivatives_Cost_Weight = training()

print(Weights)


def gradient_descend(iterations = 10000, alpha = 0.01, dW_matrix = derivatives_Cost_Weight):
	dW_matrix = np.array(dW_matrix)
	for i in range(len(derivatives_Cost_Weight)):
		dW_matrix[i] = np.array(dW_matrix[i])

	for i in range(500):
		for layer in range(len(dW_matrix)):
			for m in range(len(dW_matrix[layer][:,0])):
				for n in range(len(dW_matrix[layer][0,:])):
					a = dW_matrix[layer][m][n]
					j = Weights[layer][m][n]
					Weights[layer][m][n] = j - alpha*a
		

[array([[0.61, 0.41, 0.52, 0.06, 0.35, 0.72],
       [0.01, 0.55, 0.27, 0.47, 0.69, 0.11],
       [0.6 , 0.67, 0.26, 0.78, 0.6 , 0.07],
       [0.46, 0.17, 0.28, 0.92, 0.21, 0.96],
       [0.57, 0.77, 0.23, 0.65, 0.85, 0.23],
       [0.05, 0.15, 0.03, 0.22, 0.61, 0.88],
       [0.54, 0.11, 0.55, 0.81, 0.12, 0.19]])
 array([[0.4 , 0.8 , 0.01, 0.49, 0.43, 0.18, 0.67],
       [0.52, 0.26, 0.08, 0.82, 0.28, 0.57, 0.33],
       [0.7 , 0.52, 0.98, 0.17, 0.46, 0.89, 0.61],
       [0.08, 0.17, 0.95, 0.92, 0.77, 1.  , 0.96],
       [0.2 , 0.78, 0.53, 0.16, 0.13, 0.16, 0.19],
       [0.38, 0.23, 0.23, 0.53, 0.19, 0.27, 0.72],
       [0.41, 0.99, 0.64, 0.3 , 0.33, 0.16, 0.47]])
 array([[0.24, 0.87, 0.1 , 0.65, 0.37, 0.02, 0.75],
       [0.07, 0.44, 0.28, 0.49, 0.52, 0.44, 0.52]])]


In [18]:
gradient_descend()
print(Weights)

[array([[ 0.61      ,  0.41      ,  0.52      ,  0.06      ,  0.35      ,
         0.72      ],
       [-0.03722363,  0.53232409,  0.25407466,  0.46777525,  0.68447366,
         0.0803803 ],
       [ 0.56930456,  0.65949718,  0.25083137,  0.77874373,  0.59653077,
         0.051383  ],
       [ 0.43336686,  0.15795055,  0.27255031,  0.9200763 ,  0.20751122,
         0.9472587 ],
       [ 0.55346544,  0.76447104,  0.22513591,  0.64925833,  0.84857218,
         0.22055315],
       [ 0.02381971,  0.1389965 ,  0.02127578,  0.21942341,  0.60804806,
         0.86591531],
       [ 0.50723789,  0.09643043,  0.54086816,  0.80975952,  0.11552137,
         0.17091503]])
 array([[0.4       , 0.8       , 0.01      , 0.49      , 0.43      ,
        0.18      , 0.67      ],
       [0.45348401, 0.21869489, 0.03023272, 0.76913341, 0.22895117,
        0.52553735, 0.28262654],
       [0.68240173, 0.50924399, 0.96697947, 0.15667414, 0.4466613 ,
        0.87838329, 0.59756757],
       [0.05863566, 0.1569759

In [19]:
mat, w = forwardPropagation(i, False, False, neurons, Weights)

In [20]:
for i in range(len(desired_outputs_testing)):
	print(inputs_testing[i])
	mat, w = forwardPropagation(i, False, False, mat, Weights)
	print("Network output: ", mat[3][1], "   Desired output: ", desired_outputs_testing[i], "   ", CostFunction(mat[3][1], desired_outputs_testing[i]))


[1 1 0 0 0]
Network output:  0.0013637465562294918    Desired output:  0     -0.0005926718230810602
[1 0 1 0 1]
Network output:  0.0011480210513762678    Desired output:  1     -2.940050148163894
[0 0 0 0 0]
Network output:  0.0018584340689203702    Desired output:  0     -0.0008078585697875491
[1 1 1 1 1]
Network output:  0.0010330729211359786    Desired output:  1     -2.9858690220145223
[0 0 0 0 1]
Network output:  0.0015196631827462395    Desired output:  0     -0.0006604833179141169
[0 1 0 1 0]
Network output:  0.001314191757198564    Desired output:  1     -2.8813412610949825
[1 0 1 1 0]
Network output:  0.001138475733972842    Desired output:  1     -2.94367622171463
[1 0 0 1 0]
Network output:  0.0013034913106375508    Desired output:  1     -2.8848918595894317
[0 1 1 1 0]
Network output:  0.0011454852287130523    Desired output:  1     -2.94101050676247


In [21]:
for i in range(len(training_data_set)):
	print(inputs[i])
	mat, w = forwardPropagation(i, True, False, mat, Weights)
	print("Network output: ", mat[3][1], "   Desired output: ", desired_outputs[i], "   ", CostFunction(mat[3][1], desired_outputs[i]))


[1 1 0 0 0]
Network output:  0.0013637465562294918    Desired output:  0     -0.0005926718230810602
[1 0 1 0 1]
Network output:  0.0011480210513762678    Desired output:  1     -2.940050148163894
[0 0 0 0 0]
Network output:  0.0018584340689203702    Desired output:  0     -0.0008078585697875491
[1 1 1 1 1]
Network output:  0.0010330729211359786    Desired output:  1     -2.9858690220145223
[0 0 0 0 1]
Network output:  0.0015196631827462395    Desired output:  0     -0.0006604833179141169
[0 1 0 1 0]
Network output:  0.001314191757198564    Desired output:  1     -2.8813412610949825
[1 0 1 1 0]
Network output:  0.001138475733972842    Desired output:  1     -2.94367622171463
[1 0 0 1 0]
Network output:  0.0013034913106375508    Desired output:  1     -2.8848918595894317
[0 1 1 1 0]
Network output:  0.0011454852287130523    Desired output:  1     -2.94101050676247
[1 0 1 0 0]
Network output:  0.001261178289509545    Desired output:  1     -2.899223514000377
[1 1 0 1 1]
Network output:  0