In [1]:
import numpy as np 
import random
import matplotlib.pyplot as plt
import math

In [2]:
# 5 input neurons in the input layer
# 2 hidden layers with 6 neurons each
# 2 output neurons in the output layer
# all activation functions are sigmoid


dataset_unfiltered = np.array([
	[0,		0,		0,		0,		0,		0,		1],
	[0,		0,		0,		0,		1,		0,		1],
	[0,		0,		0,		1,		0,		0,		1],
	[0,		0,		0,		1,		1,		0,		1],
	[0,		0,		1,		0,		0,		0,		1],
	[0,		0,		1,		0,		1,		0,		1],
	[0,		0,		1,		1,		0,		0,		1],
	[0,		0,		1,		1,		1,		0,		1],
	[0,		1,		0,		0,		0,		1,		0],
	[0,		1,		0,		0,		1,		0,		1],
	[0,		1,		0,		1,		0,		1,		0],
	[0,		1,		0,		1,		1,		1,		0],
	[0,		1,		1,		0,		0,		0,		1],
	[0,		1,		1,		0,		1,		0,		1],
	[0,		1,		1,		1,		0,		1,		0],
	[0,		1,		1,		1,		1,		1,		0],
	[1,		0,		0,		0,		0,		0,		1],
	[1,		0,		0,		0,		1,		0,		1],
	[1,		0,		0,		1,		0,		1,		0],
	[1,		0,		0,		1,		1,		0,		1],
	[1,		0,		1,		0,		0,		1,		0],
	[1,		0,		1,		0,		1,		1,		0],
	[1,		0,		1,		1,		0,		1,		0],
	[1,		0,		1,		1,		1,		1,		0],
	[1,		1,		0,		0,		0,		0,		1],
	[1,		1,		0,		0,		1,		0,		1],
	[1,		1,		0,		1,		0,		1,		0],
	[1,		1,		0,		1,		1,		0,		1],
	[1,		1,		1,		0,		0,		1,		0],
	[1,		1,		1,		0,		1,		1,		0],
	[1,		1,		1,		1,		0,		1,		0],
	[1,		1,		1,		1,		1,		1,		0]
	])

In [3]:
def generateRandom2DMatrix(m, n):
	return [ [random.randint(1,100)/100 for k in range(n)] for i in range(m) ]

def sigmoid(z):
	return 1/(1+np.exp(-z))

def CostFunction(NN_output,output):
	return output*(np.log10(NN_output)) + (1-output)*(np.log10(1 - NN_output))

In [4]:
data_set = [ [0 for k in range(6)] for i in range(len(dataset_unfiltered)) ]
index_data_set = 0



for k in range(len(dataset_unfiltered[:,0])):

	for i in range(dataset_unfiltered[k][5]):
		#temp = np.append( dataset_unfiltered[k][0:5], 1)
		data_set[index_data_set] = np.append( dataset_unfiltered[k][0:5], 1)
		index_data_set += 1

	for j in range(dataset_unfiltered[k][6]):
		#temp = dataset_unfiltered[k][0:5]
		data_set[index_data_set] = np.append( dataset_unfiltered[k][0:5], 0)
		index_data_set += 1

In [5]:
# Splitting dataset into training dataset and testing dataset:
# But first, we need to shuffle the entire dataset!

random.seed(99)
random.shuffle(data_set)

training_data_set = data_set[0:(math.ceil(0.70*len(data_set)))]
testing_data_set  =	data_set[(math.ceil(0.70*len(data_set))): len(data_set)]

In [6]:
print("Training dataset:   ", len(training_data_set))
print("Testing dataset:    ", len(testing_data_set))

Training dataset:    23
Testing dataset:     9


In [7]:
inputs = [ [0 for k in range(5)] for i in range(len(training_data_set)) ]
desired_outputs = [0 for k in range(len(training_data_set))]


inputs_testing = [ [0 for k in range(5)] for i in range(len(testing_data_set)) ]
desired_outputs_testing = [0 for k in range(len(testing_data_set))]



for i in range(len(training_data_set)):
	inputs[i] = training_data_set[i][0:5]
	desired_outputs[i] = training_data_set[i][5]

for i in range(len(testing_data_set)):
	inputs_testing[i] = training_data_set[i][0:5]
	desired_outputs_testing[i] = training_data_set[i][5]

In [8]:
bias_space = 1

nInputs_neurons = 5 
nNeurons_second_layer = 6 
nNeurons_third_layer  = 6 
output_neurons = 1 

nInputs_neurons += bias_space
nNeurons_second_layer += bias_space
nNeurons_third_layer  += bias_space
output_neurons += bias_space     # Not needed but will does make the algorith easier to write. We will ignore the bias here.




In [9]:
Weights = [ [] for i in range(3)]

#the first column is the Bias. So it will be set to 1.
Weights[0] = np.array(generateRandom2DMatrix(nNeurons_second_layer, nInputs_neurons ))
Weights[1] = np.array(generateRandom2DMatrix(nNeurons_third_layer, nNeurons_second_layer ))
Weights[2] = np.array(generateRandom2DMatrix(output_neurons, nNeurons_third_layer ))

Weights = np.array(Weights)

In [10]:
input_layer = [ 0 for i in range(nInputs_neurons)]
first_hidden_layer = [ 0 for i in range(nNeurons_second_layer)]
second_hidden_layer = [ 0 for i in range(nNeurons_third_layer)]
output_layer = [ 0 for i in range(output_neurons)]

In [11]:
# These are bias
input_layer = np.append(1, inputs[0])
first_hidden_layer[0] = 1
second_hidden_layer[0] = 1

neurons = [input_layer, first_hidden_layer, second_hidden_layer, output_layer]
neurons = (neurons)
#neuron["layer"]["Which neuron of the layer/ FIRST ONE IS THE BIAS"]
neurons[0][0] = 1
neurons[1][0] = 1
neurons[2][0] = 1
neurons[3][0] = 1

In [12]:
def forwardPropagation(data_number = 0, training_data = True, showComputation = False, matrix_neurons = neurons, W = Weights):
	if(training_data == True):
		input_i = inputs[data_number]
	else:
		input_i = inputs_testing[data_number]

	matrix_neurons[0] = np.append(1 , input_i)
	matrix_neurons[1][0] = 1
	matrix_neurons[2][0] = 1
	matrix_neurons[3][0] = 1
	
	if(showComputation == True):
		print(matrix_neurons)

	for layer in range(len(W)):
		for neuron_j in range(len(matrix_neurons[layer+1])):
			next_layer_neuron = layer + 1
			z_j = np.dot( matrix_neurons[layer] , W[layer][neuron_j,:] )
			matrix_neurons[next_layer_neuron][neuron_j] = sigmoid(z_j)
			if(showComputation == True):
				print(matrix_neurons[layer] ," . " , W[layer][neuron_j,:], "  = s([",next_layer_neuron, "][",neuron_j,"]]) = ", sigmoid(z_j))
				print("")

	matrix_neurons[1][0] = 1
	matrix_neurons[2][0] = 1
	matrix_neurons[3][0] = 1

	return matrix_neurons, W

In [13]:
# test
forwardPropagation(0)


def printNeurons(matrix_neurons = neurons):
	layer_names = ["Inputs        ", "Hidden layer 1", "Hidden layer 2", "Outputs       "]
	for i in range(len(matrix_neurons)):
		print(layer_names[i] , ":        ", matrix_neurons[i])
        
    
printNeurons()

Inputs         :         [1 1 1 0 0 0]
Hidden layer 1 :         [1, 0.6963549298238342, 0.8220063142137535, 0.7130001627522816, 0.8277836082661223, 0.5572478545985555, 0.7685247834990178]
Hidden layer 2 :         [1, 0.8872244509440987, 0.9612400717011033, 0.9721735867571986, 0.8320721031373728, 0.8700163598547583, 0.9234753293152094]
Outputs        :         [1, 0.923769115516216]


In [14]:
# Initializing delta
def get_copy_of_neurons_matrix_null(matrix):
	m = matrix.copy()
	for i in range(len(m)):
		m[i] = np.matrix(m[i])
		m[i].fill(0)
	return m



delta_error_matrix = get_copy_of_neurons_matrix_null(neurons)

In [15]:
def computeDeltaMatrix(training_example = 0, showComputation = False, W = Weights, matrix_neurons = neurons, Delt = delta_error_matrix):
	
	if(showComputation == True):
		print("STARTING: ")
	#training_example = 1000
	input_i = inputs[training_example] 
	desired_outputs_i = desired_outputs[training_example]

	if(showComputation == True):
		print(W)
		print("Training example: ", training_example)
		print("Inputs and outputs: ", input_i, desired_outputs_i)

	for layer in reversed(range(1,len(matrix_neurons))):
		if(showComputation == True):
			print(layer)
		if(layer == len(matrix_neurons) - 1):
			if(showComputation == True):
				print(np.subtract(matrix_neurons[layer][1:len(matrix_neurons[layer])] , desired_outputs_i))
			Delt[layer] = np.subtract(matrix_neurons[layer][1:len(matrix_neurons[layer])] , desired_outputs_i)
			Delt[layer] = np.append(0, Delt[layer])
		else:
				w = W[layer].copy() #[1:len(W[layer])].copy()
				
				w_T = w.transpose() 
				if(showComputation == True):
					print("w: ", w)
					print("w_T:")
					print(w_T)
					print("delta ",layer + 1,":" )
					print(Delt[layer + 1])
				x = np.matmul(w_T, Delt[layer + 1])
				#x = x[1:len(x)]

				# Derivative_Sigmoid_of_neuron_layer(z) = neurons_of_layer*(1-neurons_of_layer)
				neurons_of_layer = np.array(matrix_neurons[layer].copy())#[1:len(matrix_neurons[layer])].copy())
				vector_of_one 	 = np.array(neurons_of_layer.copy())
				vector_of_one.fill(1)
				y = np.subtract(vector_of_one, neurons_of_layer)
				Derivative_Sigmoid_of_neuron_layer = np.multiply(neurons_of_layer , y)

				# Putting the whole equation together:
				Delt[layer] = np.multiply(x , Derivative_Sigmoid_of_neuron_layer)
		if(showComputation == True):
			print("delta[",layer,"]", Delt[layer])
	return Delt

In [65]:
delta = computeDeltaMatrix() 
#print(np.matrix(delta))


def training(nomber_of_training_set = len(training_data_set), matrix_neurons = neurons, W = Weights, regularization_param = 0):
	mat_weights_null = get_copy_of_neurons_matrix_null(W)
	
	for training_set in range(nomber_of_training_set):
		#print(training_set)
		matrix_neurons, W 	= forwardPropagation(training_set, True, False, matrix_neurons, W)
		delta 				= computeDeltaMatrix(training_set)

		# Backpropagation algorithm
		for layer in reversed(range(1, len(matrix_neurons))):
			neuron_vector = neurons[layer-1].copy()
			delta_vector  = delta[layer].copy()

			neuron_vector = np.matrix(neuron_vector)
			delta_vector  = np.matrix(delta_vector).transpose()

			multiplication_term = np.matmul(delta_vector, neuron_vector)
			mat_weights_null[layer-1] = mat_weights_null[layer-1] + multiplication_term

	c = (1/nomber_of_training_set)
	#derivative_J = (1/nomber_of_training_set)*mat_weights_null
	derivatives_Cost_Weight = get_copy_of_neurons_matrix_null(W)

	for layer in range(len(mat_weights_null)):
		for m in range(len(mat_weights_null[layer][:,0])):
			for n in range(len(mat_weights_null[layer][0,:])):
				if(n != 0):
					derivatives_Cost_Weight[layer][m][n] = c*mat_weights_null[layer][m][n] #+ regularization_param*W[layer][m][n]
				else:
					derivatives_Cost_Weight[layer][m][n] = c*mat_weights_null[layer][m][n]
	return derivatives_Cost_Weight

In [67]:
derivatives_Cost_Weight = training()

print(Weights)


def gradient_descend(iterations = 60000, alpha = 0.01, dW_matrix = derivatives_Cost_Weight):
	dW_matrix = np.array(dW_matrix)
	for i in range(len(derivatives_Cost_Weight)):
		dW_matrix[i] = np.array(dW_matrix[i])

	for i in range(iterations):
		for layer in range(len(dW_matrix)):
			for m in range(len(dW_matrix[layer][:,0])):
				for n in range(len(dW_matrix[layer][0,:])):
					a = dW_matrix[layer][m][n]
					j = Weights[layer][m][n]
					Weights[layer][m][n] = j - alpha*a
		

[array([[  0.61      ,   0.41      ,   0.52      ,   0.06      ,
          0.35      ,   0.72      ],
       [ -2.62110604,  -1.64718624,  -0.91529618,  -1.94527309,
         -1.01534079,  -1.54621229],
       [-34.84471769, -20.02698368, -23.02886515, -21.54699888,
        -20.78502002, -15.78393808],
       [ 15.82406266,   9.42698631,  10.80432239,  11.9157419 ,
          9.4569715 ,   6.08592847],
       [  3.22140778,   1.32901867,   2.48086026,   1.03213979,
          1.60760115,   0.20588913],
       [-49.13423317, -31.2894703 , -31.47048948, -33.6384943 ,
        -30.07376672, -19.74137359],
       [-29.66197329, -19.18986969, -18.1118989 , -19.26222573,
        -18.81921246, -13.03533483]])
 array([[ 4.00000000e-01,  8.00000000e-01,  1.00000000e-02,
         4.90000000e-01,  4.30000000e-01,  1.80000000e-01,
         6.70000000e-01],
       [-8.56972587e+01, -3.41771705e+01, -6.14602287e+01,
        -5.95494089e+01, -7.00238895e+01, -4.46715388e+01,
        -5.26143302e+01],
  

In [68]:
gradient_descend()
print(Weights)

[array([[  0.61      ,   0.41      ,   0.52      ,   0.06      ,
          0.35      ,   0.72      ],
       [ -2.62110604,  -1.64718624,  -0.91529618,  -1.94527309,
         -1.01534079,  -1.54621229],
       [-34.84471769, -20.02698368, -23.02886515, -21.54699888,
        -20.78502002, -15.78393808],
       [ 15.82406266,   9.42698631,  10.80432239,  11.9157419 ,
          9.4569715 ,   6.08592847],
       [  3.22140778,   1.32901867,   2.48086026,   1.03213979,
          1.60760115,   0.20588913],
       [-49.13423317, -31.2894703 , -31.47048948, -33.6384943 ,
        -30.07376672, -19.74137359],
       [-29.66197329, -19.18986969, -18.1118989 , -19.26222573,
        -18.81921246, -13.03533483]])
 array([[ 4.00000000e-01,  8.00000000e-01,  1.00000000e-02,
         4.90000000e-01,  4.30000000e-01,  1.80000000e-01,
         6.70000000e-01],
       [-8.56972587e+01, -3.41771705e+01, -6.14602287e+01,
        -5.95494089e+01, -7.00238895e+01, -4.46715388e+01,
        -5.26143302e+01],
  

In [63]:
mat, w = forwardPropagation(0, False, False, neurons, Weights)

In [64]:
x = [-1/10000000 for i in range(len(desired_outputs_testing))]
x = np.array(x)
y = x.copy()


for i in range(len(desired_outputs_testing)):
	print(inputs_testing[i])
	mat, w = forwardPropagation(i, False, False, mat, Weights)
	x[i] = mat[3][1]
	y[i] = desired_outputs_testing[i]
	print("Network output: ", mat[3][1], "   Desired output: ", desired_outputs_testing[i], "   ", CostFunction(mat[3][1], desired_outputs_testing[i]))

[1 1 0 0 0]
Network output:  0.9998976846373853    Desired output:  0     -3.9900591522322135
[1 0 1 0 1]
Network output:  0.9998995050090798    Desired output:  1     -4.3646613185311055e-05
[0 0 0 0 0]
Network output:  0.9998896782574364    Desired output:  0     -3.95733888697181
[1 1 1 1 1]
Network output:  0.9999057404301642    Desired output:  1     -4.0938340491746004e-05
[0 0 0 0 1]
Network output:  0.9998937391744854    Desired output:  0     -3.973626814484723
[0 1 0 1 0]
Network output:  0.9998977733281047    Desired output:  1     -4.4398748914299e-05
[1 0 1 1 0]
Network output:  0.9998954730349672    Desired output:  1     -4.539785681528253e-05
[1 0 0 1 0]
Network output:  0.9998952724871705    Desired output:  1     -4.5484962730399734e-05
[0 1 1 1 0]
Network output:  0.9998970602457488    Desired output:  1     -4.4708468418648636e-05


In [62]:
print(x)
print(y)

x.sort()
print(x)

[0.99989768 0.99989951 0.99988968 0.99990574 0.99989374 0.99989777
 0.99989547 0.99989527 0.99989706]
[0. 1. 0. 1. 0. 1. 1. 1. 1.]
[0.99988968 0.99989374 0.99989527 0.99989547 0.99989706 0.99989768
 0.99989777 0.99989951 0.99990574]


In [21]:
for i in range(len(training_data_set)):
	print(inputs[i])
	mat, w = forwardPropagation(i, True, False, mat, Weights)
	print("Network output: ", mat[3][1], "   Desired output: ", desired_outputs[i], "   ", CostFunction(mat[3][1], desired_outputs[i]))


[1 1 0 0 0]
Network output:  2.3804422038609128e-35    Desired output:  0     0.0
[1 0 1 0 1]
Network output:  2.5156626786512466e-36    Desired output:  1     -35.5993475932036
[0 0 0 0 0]
Network output:  2.2715766724974286e-35    Desired output:  0     0.0
[1 1 1 1 1]
Network output:  4.974514478863501e-37    Desired output:  1     -36.30324930073538
[0 0 0 0 1]
Network output:  3.5722059762244084e-35    Desired output:  0     0.0
[0 1 0 1 0]
Network output:  5.6352551957549444e-36    Desired output:  1     -35.24908641189851
[1 0 1 1 0]
Network output:  6.048405246159052e-37    Desired output:  1     -36.21835911858578
[1 0 0 1 0]
Network output:  6.024398207854096e-36    Desired output:  1     -35.22008632934421
[0 1 1 1 0]
Network output:  5.894026684845551e-37    Desired output:  1     -36.22958790223992
[1 0 1 0 0]
Network output:  2.2638425339683495e-36    Desired output:  1     -35.64515378464232
[1 1 0 1 1]
Network output:  4.467084489662262e-36    Desired output:  0     0.0